docs: Create CONTRIBUTING
TypedProject/tsed-cli pull request #19
Opened 2020-10-08 16:16 UTC by loic5

2020-10-08 17:46 UTC, Romakita requested changes

2020-10-08 17:46 UTC, Romakita commented on CONTRIBUTING.md
> +$ git clone https://github.com/YOUR_USERNAME/tsed.git
git clone https://github.com/YOUR_USERNAME/tsed.git 

A remplacer par:
git clone https://github.com/YOUR_USERNAME/tsed-cli.git

2020-10-08 17:46 UTC, Romakita commented on CONTRIBUTING.md
> +> After installing dependencies, yarn/npm run the `postinstall` hook and mounted all packages with `npm link` (e.g. `yarn run repo:bootstrap`).
Tu peux supprimer cette ligne. :)

2020-10-08 17:46 UTC, Romakita commented on CONTRIBUTING.md
> +git branch --no-track -b feat-branch-name origin/production  # !IMPORTANT
production => master

2020-10-08 17:46 UTC, Romakita commented on CONTRIBUTING.md
> +This command rebases your branch feature from the production branch, runs the test, and pushes your branch.
production => master

2020-10-08 17:46 UTC, Romakita commented on CONTRIBUTING.md
> +git rebase origin/production
production => master

2020-10-08 17:47 UTC, Romakita commented
Thanks Loïc :)
There are small requested change. Ask me tomorrow to know how you can apply change on the current PR :)

2020-10-08 19:28 UTC, loic5 commented on CONTRIBUTING.md
> +$ git clone https://github.com/YOUR_USERNAME/tsed.git
done

2020-10-08 19:28 UTC, loic5 commented on CONTRIBUTING.md
> +> After installing dependencies, yarn/npm run the `postinstall` hook and mounted all packages with `npm link` (e.g. `yarn run repo:bootstrap`).
done

2020-10-08 19:28 UTC, loic5 commented on CONTRIBUTING.md
> +git branch --no-track -b feat-branch-name origin/production  # !IMPORTANT
done

2020-10-08 19:28 UTC, loic5 commented on CONTRIBUTING.md
> +This command rebases your branch feature from the production branch, runs the test, and pushes your branch.
done

2020-10-08 19:28 UTC, loic5 commented on CONTRIBUTING.md
> +git rebase origin/production
done

2020-10-09 06:04 UTC, Romakita approved these changes

2020-10-09 06:04 UTC, merged

2020-10-10 18:20 UTC, Romakita commented
:tada: This PR is included in version 2.0.0-beta.2 :tada:

The release is available on:
- `v2.0.0-beta.2`
- [GitHub release](https://github.com/TypedProject/tsed-cli/releases/tag/v2.0.0-beta.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-12 09:44 UTC, Romakita commented
:tada: This PR is included in version 2.0.0-rc.1 :tada:

The release is available on:
- `v2.0.0-rc.1`
- [GitHub release](https://github.com/TypedProject/tsed-cli/releases/tag/v2.0.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-14 16:11 UTC, Romakita commented
:tada: This PR is included in version 1.19.0 :tada:

The release is available on:
- `v1.19.0`
- [GitHub release](https://github.com/TypedProject/tsed-cli/releases/tag/v1.19.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: